In [1]:
import os
import pandas as pd

os.chdir('D:\GreyAtom\Datasets')

In [3]:
ls

 Volume in drive D is DATA
 Volume Serial Number is 347B-C42C

 Directory of D:\GreyAtom\Datasets

08-09-2018  10:06    <DIR>          .
08-09-2018  10:06    <DIR>          ..
15-07-2018  09:31               187 brics.csv
15-07-2018  09:29               179 cars.csv
08-09-2018  10:05            84,393 f500.csv
14-07-2018  09:38    <DIR>          game-of-thrones
14-07-2018  10:47           257,011 ipl_matches_small.csv
08-09-2018  10:05           199,782 laptops.csv
08-09-2018  10:04         5,145,963 nyc_taxis.csv
04-08-2018  14:58             8,413 olympics.csv
15-07-2018  15:07            14,144 populations_year.xlsx
08-09-2018  10:02           503,663 spam.csv
22-07-2018  14:31           532,885 StarWars.csv
14-07-2018  15:30           385,172 weather_small_2012.csv
15-07-2018  16:30           385,039 weather_small_2012_1.csv
21-07-2018  12:05            20,793 wnba.csv
              13 File(s)      7,537,624 bytes
               3 Dir(s)  500,048,736,256 bytes free

In [7]:
df = pd.read_csv('spam.csv', encoding = "Latin - 1")

In [9]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [10]:
df1 = df.copy()

In [11]:
list(df)

['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

In [13]:
cols_to_be_dropped = list(df)[-3:]

In [14]:
df = df.drop(cols_to_be_dropped, axis=1)

In [15]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [20]:
df = df.rename(columns={"v1":"Status", "v2":"Message"})

In [18]:
df

     Status                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
5      spam  FreeMsg Hey there darling it's been 3 week's n...
6       ham  Even my brother is not like to speak with me. ...
7       ham  As per your request 'Melle Melle (Oru Minnamin...
8      spam  WINNER!! As a valued network customer you have...
9      spam  Had your mobile 11 months or more? U R entitle...
10      ham  I'm gonna be home soon and i don't want to tal...
11     spam  SIX chances to win CASH! From 100 to 20,000 po...
12     spam  URGENT! You have won a 1 week FREE membership ...
13      ham  I've been searching for the right words to tha...
14      ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15     spam  XXXMobileMovieClub: To use your credit, click ...
16      ham                         Oh k...i'm watching here:)
17      ham  Eh u remember how 2 spell his name... Yes i di...
18      ham  Fine if thatåÕs the way u feel. ThatåÕs the wa...
19     spam  England v Macedonia - dont miss the goals/team...
20      ham          Is that seriously how you spell his name?
21      ham  IÛ÷m going to try for 2 months ha ha only joking
22      ham  So Ì_ pay first lar... Then when is da stock c...
23      ham  Aft i finish my lunch then i go str down lor. ...
24      ham  Ffffffffff. Alright no way I can meet up with ...
25      ham  Just forced myself to eat a slice. I'm really ...
26      ham                     Lol your always so convincing.
27      ham  Did you catch the bus ? Are you frying an egg ...
28      ham  I'm back &amp; we're packing the car now, I'll...
29      ham  Ahhh. Work. I vaguely remember that! What does...
...     ...                                                ...
5542    ham           Armand says get your ass over to epsilon
5543    ham             U still havent got urself a jacket ah?
5544    ham  I'm taking derek &amp; taylor to walmart, if I...
5545    ham      Hi its in durban are you still on this number
5546    ham         Ic. There are a lotta childporn cars then.
5547   spam  Had your contract mobile 11 Mnths? Latest Moto...
5548    ham                 No, I was trying it all weekend ;V
5549    ham  You know, wot people wear. T shirts, jumpers, ...
5550    ham        Cool, what time you think you can get here?
5551    ham  Wen did you get so spiritual and deep. That's ...
5552    ham  Have a safe trip to Nigeria. Wish you happines...
5553    ham                        Hahaha..use your brain dear
5554    ham  Well keep in mind I've only got enough gas for...
5555    ham  Yeh. Indians was nice. Tho it did kane me off ...
5556    ham  Yes i have. So that's why u texted. Pshew...mi...
5557    ham  No. I meant the calculation is the same. That ...
5558    ham                             Sorry, I'll call later
5559    ham  if you aren't here in the next  &lt;#&gt;  hou...
5560    ham                  Anything lor. Juz both of us lor.
5561    ham  Get me out of this dump heap. My mom decided t...
5562    ham  Ok lor... Sony ericsson salesman... I ask shuh...
5563    ham                                Ard 6 like dat lor.
5564    ham  Why don't you wait 'til at least wednesday to ...
5565    ham                                       Huh y lei...
5566   spam  REMINDER FROM O2: To get 2.50 pounds free call...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [37]:
Laptops = pd.read_csv('laptops.csv', encoding = "Latin - 1", skipinitialspace = True)

In [38]:
Laptops.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros)
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45"
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60"

In [47]:
list(Laptops)

['manufacturer',
 'model_name',
 'category',
 'screen_size',
 'screen',
 'cpu',
 'ram',
 'storage',
 'gpu',
 'operating_system',
 'operating_system_version',
 'weight',
 'price_euros']

In [111]:
import re
Laptops = pd.read_csv('laptops.csv', encoding = "Latin - 1", skipinitialspace = True)

Laptops.columns = [x.lower() for x in Laptops.columns]
Laptops.columns = [x.replace(" ", "_") for x in Laptops.columns]
Laptops.columns = [x.replace("(", "") for x in Laptops.columns]
Laptops.columns = [x.replace(")", "") for x in Laptops.columns]

Laptops["screen_size"] = Laptops["screen_size"].str.replace('"', '').astype(float)
Laptops["ram"] = Laptops["ram"].str.replace('GB', '').astype(int)

Laptops["weight"] = Laptops["weight"].str.replace("kg", "", regex=True)
Laptops["weight"] = Laptops["weight"].str.replace("s", "", regex=True).astype(float)

Laptops["price_euros"] = Laptops["price_euros"].str.replace(',', '.').astype(float)
#Laptops["weight"] = Laptops["weight"].str.replace("kg*", "", regex=True).astype(float)

Laptops.rename({"screen_size":"screen_size_inches", "ram":"ram_gb", "weight":"weight_kgs"}, axis=1, inplace=True)
Laptops.sort_values(['screen_size_inches', 'ram_gb'], ascending=True)

#Laptops["gpu_m"] = Laptops["gpu"].str.split(n=1,expand=True).iloc[:,0]
Laptops["gpu_m"] = Laptops.apply(lambda row: row['gpu'].split()[0], axis=1)
Laptops["cpu_m"] = Laptops.apply(lambda row: row['cpu'].split()[0], axis=1)
#Laptops["resolution"] = Laptops.apply(lambda row: row['screen'].split().str.get(-1), axis=1)
Laptops["resolution"] = Laptops["screen"].str.split().str.get(-1)

#Laptops.isnull().sum()
Laptops.to_csv('clean_laptops.csv')