In [7]:
import pandas as pd

a = [1, 2, 3]
b = [3, 4, 5]
c = [5, 6, 7]
d = [7, 8, 9]

df2 = pd.DataFrame([a, b, c, d], index=["a", "b", "c", "d"], columns = ["x", "y", "z"])
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
x    4 non-null int64
y    4 non-null int64
z    4 non-null int64
dtypes: int64(3)
memory usage: 128.0+ bytes

In [9]:
import os
os.chdir("D:\GreyAtom\Datasets")

In [10]:
weather = pd.read_csv("weather_small_2012_1.csv")
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 7 columns):
Date/Time             8784 non-null object
Temp (C)              8784 non-null float64
Dew Point Temp (C)    8777 non-null float64
Rel Hum (%)           8773 non-null float64
Wind Spd (km/h)       8776 non-null float64
Visibility (km)       8778 non-null float64
Stn Press (kPa)       8776 non-null float64
dtypes: float64(6), object(1)
memory usage: 480.5+ KB

In [11]:
weather['Temp (C)'].unique()

array([ -1.8,  -1.5,  -1.4,  -1.3,  -1. ,  -0.5,  -0.2,   0.2,   0.8,
         1.8,   2.6,   3. ,   3.8,   3.1,   3.2,   4. ,   4.4,   5.3,
         5.2,   4.6,   3.9,   3.7,   2.9,   2.3,   2. ,   1.9,   1.5,
         2.2,   1.7,   1.1,   0. ,  -0.7,  -2.1,  -4.1,  -4.8,  -5.6,
        -5.8,  -7. ,  -7.4,  -9. ,  -9.7, -10.5, -11.3, -12.6, -12.9,
       -13.3, -14. , -14.8, -15. , -15.3, -14.9, -15.1, -15.8, -16.3,
       -16.9, -17.3, -17. , -17.1, -17.5, -17.9, -18.1, -18.5, -18.6,
       -18.2, -17.8, -16.8, -15.2, -14.2, -13.7, -12.4, -10.2,  -9.4,
        -8.9,  -8.4,  -7.8,  -7.6,  -9.5,  -9.6,  -8.8,  -7.5,  -5.4,
        -5. ,  -8.2,  -7.1,  -6.1,  -6.6,  -6. ,  -4.7,  -4.4,  -5.1,
        -4.3,  -6.7,  -9.2,  -9.8,  -9.9, -10. , -10.6, -11.8, -12. ,
       -14.4, -12.3, -12.5, -11.7, -11.9, -11.2, -11.5, -11.6,  -9.3,
        -8.7,  -8.5,  -8.1,  -6.9,  -6.4,  -5.7,  -5.5,  -3.7,  -3.6,
        -3.1,  -3.2,  -3. ,   0.4,   0.6,  -0.6,  -1.7,  -3.5,  -5.9,
        -6.5,  -7.2,  -8. ,  -8.3,  -7.7,  -6.8,  -2.5,  -1.1,  -0.3,
         2.5,   1.4,   1.6,   1.2,   0.7,  -4. ,  -4.9,  -7.3,  -8.6,
       -10.7, -12.7, -13.4, -13.9, -14.7, -14.3, -12.2, -11.4, -10.8,
        -6.2,  -5.2,  -4.6,  -4.5,  -2.9, -18. , -16.7, -17.4, -17.7,
       -18.3, -19.6, -20. , -19.9, -20.3, -21.2, -21.1, -21.4, -20.7,
       -21. , -21.3, -23.2, -22.8, -23.3, -22.2, -20.6, -19.3, -16. ,
       -15.4, -16.2, -19.2, -18.7, -19.1, -13.6, -10.1, -10.4,  -5.3,
        -3.3,  -1.6,   2.1,   0.5, -10.9, -11.1, -11. , -10.3, -16.6,
       -14.6,  -4.2,  -3.9,  -6.3, -15.5, -15.9, -16.4, -16.1, -12.1,
       -13. , -17.6, -18.4, -17.2, -19.5, -19. , -14.5, -13.2,   2.7,
         3.3,   3.6,   3.5,   5. ,   4.2,   3.4,   2.8,   2.4,   1.3,
         1. ,  -0.1,  -0.4,  -2.8,  -7.9,  -3.4,  -3.8,  -0.8,   0.3,
         0.1,  -1.2,   0.9,  -0.9,  -2. ,  -1.9,  -2.2,  -2.3, -15.7,
       -13.5, -13.8,  -2.4, -13.1, -12.8,  -2.7,   5.8,   6.1,   5.4,
         6.5,   4.3,   6.4,   8.9,   9.3,   9.7,  11.4,   9.9,   5.5,
         6. ,   7.6,   6.8,   4.8,   6.2,   7.9,  10.1,  10. ,   5.7,
        10.3,   6.7,  10.2,  12.1,  12.7,  11.7,  11.5,  11.6,  11.3,
        10.5,  -2.6,   5.9,   9. ,   9.5,  10.9,  10.7,   9.1,   7.4,
         8.3,  10.6,  10.8,  12.3,  12.4,  11.8,   8.7,   9.2,   8.4,
         6.6,   7.5,   5.1,   4.9,   4.1,   8.1,   9.8,   8.8,   7.7,
        10.4,  11.9,  14.1,  17.3,  20. ,  21.7,  22.2,  22.7,  21.8,
        18.4,  17.1,  12.8,  13.4,  12.6,  11.2,  13.9,  15.6,  17.8,
        19.8,  18.5,  17. ,  16.3,  16.6,  15.9,  12.5,   7.2,   7.1,
         8. ,  14.9,  16.5,  21.5,  22.5,  23.3,  22. ,  19.7,  17.5,
        18.1,  16. ,  14.2,  14.3,  14. ,  13.8,  18.2,  20.2,  22.3,
        23.8,  24.7,  25.4,  25.5,  25.2,  20.7,  17.2,  16.4,  18. ,
        15.5,  15. ,  11. ,  13.2,  13.7,  15.4,  19.6,  20.4,  23. ,
        22.8,  21.4,  16.7,  15.1,  14.5,  16.2,  16.8,  14.7,   7.3,
         4.7,   6.3,   4.5,   8.2,   7. ,   6.9,   7.8,   5.6,   8.5,
         8.6,   9.4,  12.2,  13.5,  16.1,  13.6,  15.3,  14.8,  12. ,
        12.9,  13.1,  19.4,  14.6,  15.7,  14.4,  15.2,  19.3,  24.9,
        24.1,  24.8,  26.6,  27.4,  27.8,  27.3,  26.7,  26.4,  20.5,
        19.5,  19. ,  18.9,  17.4,  11.1,  15.8,  18.7,   9.6,  13. ,
        13.3,  16.9,  20.1,  20.6,  20.9,  21. ,  19.9,  19.2,  17.6,
        17.9,  18.6,  22.4,  23.9,  23.6,  18.8,  21.2,  21.9,  23.2,
        23.4,  23.5,  22.9,  18.3,  20.3,  20.8,  17.7,  19.1,  25.6,
        25.8,  26. ,  24.3,  21.6,  26.8,  28.6,  29.5,  30.9,  31.2,
        30.8,  29.2,  26.9,  25.9,  24. ,  28. ,  28.4,  28.8,  28.9,
        28.2,  27.7,  26.5,  21.1,  24.6,  26.1,  27.1,  27.6,  28.1,
        24.4,  23.1,  27.2,  26.2,  21.3,  22.1,  22.6,  24.2,  23.7,
        25.3,  28.7,  29.4,  30.1,  29.6,  29.1,  25. ,  24.5,  25.7,
        27. ,  27.9,  26.3,  28.5,  29.7,  31.7,  32.2,  32.3,  32.4,
        30.6,  25.1,  31.8,  31.6,  32.6,  33. ,  32.5,  32.1,  31.1,
        30.3,  27.5,  29. ,  29.8,  30.7,  30.2,  29.9,  28.3,  30.5,
        30.4,  31.9,  31.4,  32.7,  32.9,  31.5,  29.3,  30. ,  32. ,
        32.8,  -9.1])

In [12]:
weather['Temp (C)'].nunique()

533

In [13]:
weather = pd.read_csv("weather_small_2012.csv")
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 7 columns):
Date/Time             8784 non-null object
Temp (C)              8784 non-null float64
Dew Point Temp (C)    8784 non-null float64
Rel Hum (%)           8784 non-null int64
Wind Spd (km/h)       8784 non-null int64
Visibility (km)       8784 non-null float64
Stn Press (kPa)       8784 non-null float64
dtypes: float64(4), int64(2), object(1)
memory usage: 480.5+ KB

In [14]:
weather.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
0,01-01-2012 00:00,-1.8,-3.9,86,4,8.0,101.24
1,01-01-2012 01:00,-1.8,-3.7,87,4,8.0,101.24
2,01-01-2012 02:00,-1.8,-3.4,89,7,4.0,101.26
3,01-01-2012 03:00,-1.5,-3.2,88,6,4.0,101.27
4,01-01-2012 04:00,-1.5,-3.3,88,7,4.8,101.23

In [16]:
weather["Dew Point Temp (C)"].value_counts()

-0.9     48
 12.9    48
 9.9     47
 10.9    47
 12.3    45
-0.3     45
 16.7    45
 9.6     43
 10.4    42
 8.9     42
 8.4     42
 11.2    41
 11.0    41
-1.0     41
 7.9     41
 17.8    40
-5.1     40
 16.1    40
 10.5    39
 15.3    39
 12.6    39
 0.2     38
-1.5     38
 16.9    38
 12.8    38
 12.7    37
 11.8    37
-2.1     37
 12.2    36
 10.7    36
         ..
-28.5     2
-22.7     2
-24.8     2
-22.3     2
 24.4     1
 21.9     1
-27.8     1
-26.2     1
-26.0     1
 23.2     1
 22.6     1
-24.5     1
-25.6     1
-24.0     1
-23.1     1
 21.8     1
-25.9     1
-21.6     1
 22.9     1
-25.4     1
-26.5     1
 22.3     1
-25.8     1
-28.0     1
-25.5     1
-25.3     1
 23.0     1
-20.5     1
 23.1     1
-18.5     1
Name: Dew Point Temp (C), Length: 489, dtype: int64

In [19]:
ipl = pd.read_csv("ipl_matches_small.csv")
ipl.head()

,match_code,date,city,team1,team2,toss_winner,toss_decision,winner,win_type,win_margin,...,batsman,non_striker,bowler,runs,extras,total,extras_type,player_out,wicket_kind,wicket_fielders
0,392203,01-05-2009,East London,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,9,...,ST Jayasuriya,SR Tendulkar,I Sharma,0,1,1,wides,NaN,NaN,NaN
1,392203,01-05-2009,East London,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,9,...,ST Jayasuriya,SR Tendulkar,I Sharma,1,0,1,NaN,NaN,NaN,NaN
2,392203,01-05-2009,East London,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,9,...,SR Tendulkar,ST Jayasuriya,I Sharma,0,1,1,wides,NaN,NaN,NaN
3,392203,01-05-2009,East London,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,9,...,SR Tendulkar,ST Jayasuriya,I Sharma,0,0,0,NaN,NaN,NaN,NaN
4,392203,01-05-2009,East London,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,9,...,SR Tendulkar,ST Jayasuriya,I Sharma,2,0,2,NaN,NaN,NaN,NaN

In [24]:
ipl[["toss_winner", "toss_decision"]][1:11]

       toss_winner toss_decision
1   Mumbai Indians           bat
2   Mumbai Indians           bat
3   Mumbai Indians           bat
4   Mumbai Indians           bat
5   Mumbai Indians           bat
6   Mumbai Indians           bat
7   Mumbai Indians           bat
8   Mumbai Indians           bat
9   Mumbai Indians           bat
10  Mumbai Indians           bat

In [26]:
weather.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
0,01-01-2012 00:00,-1.8,-3.9,86,4,8.0,101.24
1,01-01-2012 01:00,-1.8,-3.7,87,4,8.0,101.24
2,01-01-2012 02:00,-1.8,-3.4,89,7,4.0,101.26
3,01-01-2012 03:00,-1.5,-3.2,88,6,4.0,101.27
4,01-01-2012 04:00,-1.5,-3.3,88,7,4.8,101.23

In [29]:
v1 = weather.loc[(weather["Wind Spd (km/h)"] > 24) & (weather["Visibility (km)"] > 25)] 
v1

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
109,05-01-2012 13:00,-4.4,-9.7,66,26,48.3,100.40
111,05-01-2012 15:00,-4.3,-12.0,55,26,48.3,100.52
350,15-01-2012 14:00,-16.0,-23.4,53,26,48.3,102.66
422,18-01-2012 14:00,-10.3,-17.6,55,28,48.3,101.19
423,18-01-2012 15:00,-10.4,-18.0,54,30,48.3,101.32
424,18-01-2012 16:00,-10.6,-18.4,53,26,48.3,101.45
425,18-01-2012 17:00,-11.3,-18.8,54,26,48.3,101.54
443,19-01-2012 11:00,-11.0,-16.9,62,26,48.3,101.56
447,19-01-2012 15:00,-6.7,-15.0,52,26,48.3,100.88
470,20-01-2012 14:00,-15.5,-24.1,48,30,48.3,101.98
471,20-01-2012 15:00,-15.0,-23.9,47,30,48.3,102.09
542,23-01-2012 14:00,2.7,-1.1,76,26,48.3,101.01
925,08-02-2012 13:00,-3.3,-12.9,47,32,48.3,101.63
927,08-02-2012 15:00,-1.8,-12.8,43,32,48.3,101.45
949,09-02-2012 13:00,0.7,-7.1,56,26,48.3,101.13
1022,12-02-2012 14:00,-13.2,-23.0,44,26,48.3,100.52
1023,12-02-2012 15:00,-12.5,-22.8,42,28,48.3,100.51
1024,12-02-2012 16:00,-12.0,-21.9,44,32,48.3,100.54
1042,13-02-2012 10:00,-6.8,-19.1,37,26,48.3,100.59
1138,17-02-2012 10:00,2.5,-3.0,67,41,48.3,100.76
1139,17-02-2012 11:00,2.6,-4.0,62,32,48.3,100.77
1352,26-02-2012 08:00,-12.1,-18.0,61,26,48.3,102.23
1353,26-02-2012 09:00,-11.6,-18.6,56,32,48.3,102.32
1355,26-02-2012 11:00,-10.1,-20.1,44,26,48.3,102.39
1356,26-02-2012 12:00,-9.3,-18.6,47,28,48.3,102.42
1357,26-02-2012 13:00,-8.3,-17.4,48,26,48.3,102.41
1358,26-02-2012 14:00,-7.6,-17.2,46,28,48.3,102.42
1359,26-02-2012 15:00,-7.1,-16.3,48,26,48.3,102.49
1379,27-02-2012 11:00,-8.7,-14.2,64,28,48.3,101.74
1500,03-03-2012 12:00,5.2,-3.0,55,37,48.3,98.82
...,...,...,...,...,...,...,...
6829,11-10-2012 13:00,9.2,-1.8,46,30,48.3,101.22
6830,11-10-2012 14:00,9.7,-1.7,45,26,48.3,101.20
6831,11-10-2012 15:00,9.8,-2.9,41,30,48.3,101.21
6832,11-10-2012 16:00,9.8,-2.7,41,28,48.3,101.18
6875,13-10-2012 11:00,7.7,-3.7,44,28,48.3,102.46
6926,15-10-2012 14:00,17.8,9.3,57,30,48.3,99.65
6998,18-10-2012 14:00,19.3,5.8,41,28,48.3,100.78
6999,18-10-2012 15:00,18.6,3.6,37,26,48.3,100.78
7000,18-10-2012 16:00,18.3,3.8,38,28,48.3,100.69
7090,22-10-2012 10:00,11.2,5.6,68,26,48.3,101.01
7091,22-10-2012 11:00,12.7,6.3,65,30,48.3,101.06
7095,22-10-2012 15:00,14.6,5.0,52,28,48.3,101.05
7619,13-11-2012 11:00,4.8,-2.0,61,30,48.3,102.09
7620,13-11-2012 12:00,6.1,-1.8,57,28,48.3,102.08
7621,13-11-2012 13:00,5.3,-3.2,54,33,48.3,102.13
7906,25-11-2012 10:00,-3.0,-9.5,61,32,48.3,100.33
7907,25-11-2012 11:00,-2.9,-9.6,60,35,48.3,100.28
7908,25-11-2012 12:00,-2.5,-9.9,57,33,48.3,100.21
7909,25-11-2012 13:00,-2.1,-9.9,55,32,48.3,100.19
7910,25-11-2012 14:00,-1.8,-10.3,52,30,48.3,100.22
7911,25-11-2012 15:00,-1.8,-10.9,50,28,48.3,100.22
7935,26-11-2012 15:00,-0.9,-9.9,50,26,48.3,101.48
8361,14-12-2012 09:00,2.3,-3.1,67,26,48.3,101.32
8408,16-12-2012 08:00,-9.5,-14.8,65,32,48.3,101.85
8704,28-12-2012 16:00,-7.7,-11.0,77,30,48.3,101.25
8748,30-12-2012 12:00,-12.2,-15.7,75,26,48.3,100.91
8749,30-12-2012 13:00,-12.4,-16.2,73,37,48.3,100.92
8750,30-12-2012 14:00,-11.8,-16.1,70,37,48.3,100.96
8751,30-12-2012 15:00,-11.3,-15.6,70,32,48.3,101.05
8752,30-12-2012 16:00,-11.4,-15.5,72,26,48.3,101.15

In [30]:
v1 = weather.loc[(weather["Wind Spd (km/h)"] > 24) | (weather["Visibility (km)"] > 25)] 
v1

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
23,01-01-2012 23:00,5.3,2.0,79,30,25.0,99.31
24,02-01-2012 00:00,5.2,1.5,77,35,25.0,99.26
25,02-01-2012 01:00,4.6,0.0,72,39,25.0,99.26
26,02-01-2012 02:00,3.9,-0.9,71,32,25.0,99.26
27,02-01-2012 03:00,3.7,-1.5,69,33,25.0,99.30
28,02-01-2012 04:00,2.9,-2.3,69,32,25.0,99.26
29,02-01-2012 05:00,2.6,-2.3,70,32,25.0,99.21
30,02-01-2012 06:00,2.3,-2.6,70,26,25.0,99.18
31,02-01-2012 07:00,2.0,-2.9,70,33,25.0,99.14
32,02-01-2012 08:00,1.9,-3.3,68,39,24.1,99.14
33,02-01-2012 09:00,1.8,-3.7,67,44,24.1,99.14
34,02-01-2012 10:00,1.5,-4.1,66,43,24.1,99.18
35,02-01-2012 11:00,2.2,-3.5,66,30,24.1,99.19
36,02-01-2012 12:00,1.7,-6.2,56,48,24.1,99.21
37,02-01-2012 13:00,1.1,-6.5,57,37,24.1,99.27
38,02-01-2012 14:00,1.1,-6.8,56,33,24.1,99.33
39,02-01-2012 15:00,0.0,-7.0,59,33,24.1,99.41
42,02-01-2012 18:00,-4.1,-11.4,57,28,25.0,99.86
45,02-01-2012 21:00,-5.8,-12.8,58,26,25.0,100.15
48,03-01-2012 00:00,-9.0,-16.0,57,28,25.0,100.35
51,03-01-2012 03:00,-11.3,-18.7,54,33,25.0,100.61
56,03-01-2012 08:00,-14.8,-21.3,58,26,24.1,101.07
106,05-01-2012 10:00,-6.0,-10.0,73,17,48.3,100.45
107,05-01-2012 11:00,-5.6,-10.2,70,22,48.3,100.41
108,05-01-2012 12:00,-4.7,-9.6,69,20,48.3,100.38
109,05-01-2012 13:00,-4.4,-9.7,66,26,48.3,100.40
110,05-01-2012 14:00,-5.1,-10.7,65,22,48.3,100.46
111,05-01-2012 15:00,-4.3,-12.0,55,26,48.3,100.52
129,06-01-2012 09:00,-12.5,-16.7,71,26,19.3,100.53
130,06-01-2012 10:00,-12.3,-16.3,72,28,16.1,100.47
...,...,...,...,...,...,...,...
8678,27-12-2012 14:00,-5.2,-6.7,89,46,0.6,100.35
8679,27-12-2012 15:00,-5.0,-6.2,91,37,0.6,100.37
8680,27-12-2012 16:00,-4.5,-6.2,88,37,2.0,100.44
8681,27-12-2012 17:00,-4.2,-5.9,88,32,3.2,100.47
8682,27-12-2012 18:00,-4.0,-5.7,88,28,8.0,100.49
8683,27-12-2012 19:00,-3.9,-5.6,88,26,9.7,100.52
8684,27-12-2012 20:00,-3.7,-5.3,89,37,16.1,100.58
8699,28-12-2012 11:00,-6.2,-8.8,82,24,48.3,101.24
8700,28-12-2012 12:00,-7.2,-9.9,81,24,48.3,101.22
8701,28-12-2012 13:00,-6.8,-9.8,79,20,48.3,101.17
8702,28-12-2012 14:00,-6.5,-9.9,77,22,48.3,101.17
8703,28-12-2012 15:00,-6.8,-10.3,76,24,48.3,101.22
8704,28-12-2012 16:00,-7.7,-11.0,77,30,48.3,101.25
8705,28-12-2012 17:00,-8.6,-12.0,76,26,25.0,101.34
8730,29-12-2012 18:00,-9.3,-10.9,88,26,6.4,100.38
8731,29-12-2012 19:00,-9.5,-11.2,87,26,3.2,100.33
8747,30-12-2012 11:00,-11.9,-15.4,75,32,24.1,100.89
8748,30-12-2012 12:00,-12.2,-15.7,75,26,48.3,100.91
8749,30-12-2012 13:00,-12.4,-16.2,73,37,48.3,100.92
8750,30-12-2012 14:00,-11.8,-16.1,70,37,48.3,100.96
8751,30-12-2012 15:00,-11.3,-15.6,70,32,48.3,101.05
8752,30-12-2012 16:00,-11.4,-15.5,72,26,48.3,101.15
8753,30-12-2012 17:00,-12.1,-15.8,74,28,25.0,101.26
8755,30-12-2012 19:00,-13.4,-16.5,77,26,25.0,101.47
8759,30-12-2012 23:00,-12.1,-15.1,78,28,25.0,101.52
8760,31-12-2012 00:00,-11.1,-14.4,77,26,25.0,101.51
8779,31-12-2012 19:00,0.1,-2.7,81,30,9.7,100.13
8781,31-12-2012 21:00,-0.5,-1.5,93,28,4.8,99.95
8782,31-12-2012 22:00,-0.2,-1.8,89,28,9.7,99.91
8783,31-12-2012 23:00,0.0,-2.1,86,30,11.3,99.89